Adoption/Adoption/Models/Animal.cs
namespace Adoption.Models.Data;

public class Animal
{
    public int Id { get; set; }
    public string Image { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }

    public int Age { get; set; }
    public string Breed { get; set; }


}

Adoption/Adoption/Models/Data/AppDbContext.cs
using Microsoft.EntityFrameworkCore;
namespace Adoption.Models.Data;


    public class AppDbContext: DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
        {

        }
        //What tables are in my database?
        public DbSet<Animal> Animals { get; set; }
    }

Adoption/Adoption/Models/ErrorViewModel.cs
namespace Adoption.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Adoption/Adoption/Controllers/AnimalController.cs
using Adoption.Models.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Adoption.Controllers
{
    public class AnimalController : Controller
    {
        private readonly AppDbContext _dbContext;

        public AnimalController(AppDbContext context)
        {
            _dbContext = context;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult SearchAnimals(string breedInput)
        {
            //SELECT * FROM Animals
            var animals = _dbContext.Animals.Where(x=>x.Breed == breedInput).ToList();
            return View(animals);
        }


        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Animal animal)
        {
            if (ModelState.IsValid)
            {
                _dbContext.Animals.Add(animal);
                _dbContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(animal);
        }
        [HttpPost]
        public IActionResult Adopt(int id)
        {
            var animal = _dbContext.Animals.Find(id);
            if (animal != null)
            {
                _dbContext.Animals.Remove(animal);
                _dbContext.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

Adoption/Adoption/Controllers/HomeController.cs
using Adoption.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Adoption.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Adoption/Adoption/Views/Animal/SearchAnimals.cshtml
@model List<Adoption.Models.Data.Animal>

@foreach (var animal in Model)
{
    <img src="@animal.Image" alt="@animal.Name" width="100" />
    <p>@animal.Name</p>
    <p>@animal.Description</p>
    <p>@animal.Breed</p>
    <p>@animal.Age</p>

    <form asp-action="Adopt" method="post">
        <input type="hidden" name="id" value="@animal.Id" />
        <input type="submit" value="Adopt" />
    </form>
}
<a href="@Url.Action("Index")">Back to Home</a>

Adoption/Adoption/Views/Home/Add.cshtml
<form asp-action="Add" method="post">
    <div>
        <label>Name</label>
        <input type="text" name="Name" />
    </div>
    <div>
        <label>Description</label>
        <textarea name="Description"></textarea>
    </div>
    <div>
        <label>Breed</label>
        <input type="text" name="Breed" />
    </div>
    <div>
        <label>Age</label>
        <input type="number" name="Age" />
    </div>
    <div>
        <label>Image URL</label>
        <input type="text" name="Img" />
    </div>
    <input type="submit" value="Add Animal" />
</form>
<a href="@Url.Action("Index")>Back to Home</a>

Adoption/Adoption/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<form asp-action="SearchAnimals" asp-controller="Animal" method="post">
    <div class="form-group">
        <label for="simpleInput"> Type in breed:</label>
        <input type="text" name="breedInput" />
    </div>
    <button type ="submit">Submit</button>
</form>
<a href="@Url.Action("Index")">Back to Home</a>

Adoption/Adoption/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Adoption</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Adoption.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Adoption</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Adoption - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>